#!/usr/bin/env ruby

=begin
author: Yuya Nishida <yuya@j96.org>
licence: X11
id: $Id: amrit,v 1.3 2002/12/04 04:05:53 yuya Exp $

amrit commands
=end

module Amrit
  autoload :VERSION, "amrit/version"

  def self.run(args)
    sleep_time = 1
    trap(:TERM) do
      exit(1)
    end
    trap(:USR1) do
      STDERR.puts("failed to run: exec(*#{args.inspect})")
      exit(2)
    end
    loop do
      fork do
        begin
          exec(*args)
        rescue
          Process.kill(:USR1, Process.ppid)
        end
      end
      pid, status = *Process.wait2
      sleep(sleep_time)
    end
  end
end

Amrit.run(ARGV)
